version: "3.9"

services:
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"  # Temporal frontend
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=app
      - POSTGRES_PWD=app
      - POSTGRES_SEEDS=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TEMPORAL_TARGET=${TEMPORAL_TARGET}
      - ORDER_TASK_QUEUE=${ORDER_TASK_QUEUE}
      - SHIPPING_TASK_QUEUE=${SHIPPING_TASK_QUEUE}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./app:/app/app
    depends_on:
      - temporal
      - postgres
    ports:
      - "8000:8000"
    command: [ "bash", "-lc", "python -m app.db && python -m app.worker & uvicorn app.api:app --host 0.0.0.0 --port 8000" ]

volumes:
  pgdata:
